### ISSUE TITLE
Wildcards do not work for selecting multiple files

### ISSUE THREAD

**Issue by jratike80** [gisinternals/buildsystem#146]
See https://github.com/OSGeo/gdal/issues/1749
The problem seems to be somehow specific to gisinternals builds or perhaps MSVC version.

This shows the issue:

```
gdaltindex test.shp *.tif
Creating new index file...
ERROR 4: `*.tif' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `*.tif' does not exist in the file system, and is not recognized as a supported dataset name.
Unable to open *.tif, skipping.
```

**Comment by rouault** [comment]
@szekerest  Jukka mentions that MSVC 2015 builds work fine with wildcards, but not 2017 ones. 

Looking at https://github.com/gisinternals/buildsystem/blob/96939d0e83eb2aed4972378404a0cd62a4c1e520/Makefile#L761 , I suspect a reason might be that "$(VCINSTALLDIR)Tools\MSVC\14.11.25503\lib\x64\setargv.obj" is not an existing file (perhaps due to a change in the revision of the compiler?), hence SETARGV would not be set

Actually, looking at the VS 2017 build log in http://build2.gisinternals.com/sdk/build-output/vc15x64-20200415-23-25-10-33-vc15x64-dev.txt, one can see that SETARGV expands to nothing

**Comment by szekerest** [comment]
Thanks for tracking it down @rouault 
Applied a fix for this

**Comment by jratike80** [comment]
Tested with some August 2020 build with gdaltindex and it worked fine.
