### ISSUE TITLE
Update to PROJ 9

### ISSUE THREAD

**Issue by ktheijs** [gisinternals/buildsystem#201]
I have a .NET application and I would like to use the network capabilities of PROJ to automatically fetch resource files when required. I have to set the environment variable `CURL_CA_BUNDLE` before I start my application to get it to work. 

A cleaner way would be to set the `ca_bundle_path` key in the proj.ini file as described here: https://proj.org/resource_files.html#proj-ini 
But that would require PROJ 9.0.

I am currently using this build https://www.gisinternals.com/query.html?content=filelist&file=release-1930-x64-gdal-3-5-3-mapserver-8-0-0.zip but it still uses PROJ 7.2.1.

Are there any plans to update PROJ to the latest version?

More info on the original problem can be found here: https://github.com/OSGeo/gdal/issues/6639

**Comment by ktheijs** [comment]
That's good news. You can let me know when it is available. I will test it.

**Comment by ktheijs** [comment]
@szekerest, is there any news on the update to PROJ 9?

**Comment by szekerest** [comment]
saw following issues in SDKShell.bat:
SET "PATH=%SDK_ROOT%bin;%SDK_ROOT%bin\gdal\python\osgeo;%SDK_ROOT%bin\proj6\apps;%SDK_ROOT%bin\gdal\apps;%SDK_ROOT%bin\ms\apps;%SDK_ROOT%bin\gdal\csharp;%SDK_ROOT%bin\ms\csharp;%SDK_ROOT%bin\curl;%PATH%"
SET "GDAL_DATA=%SDK_ROOT%bin\gdal-data"
SET "GDAL_DRIVER_PATH=%SDK_ROOT%bin\gdal\plugins"
SET "PYTHONPATH=%SDK_ROOT%bin\gdal\python;%SDK_ROOT%bin\ms\python"
SET "PROJ_LIB=%SDK_ROOT%bin\proj7\SHARE"

proj6 and proj7 should be replaced by proj9.

Symptom: otherwise you get warnings like ERROR 1: PROJ: proj_create_from_database: (...) contains DATABASE.LAYOUT.VERSION.MINOR = 5..) whereas a number >= 2 is expected. It comes from another PROJ installation. And even EPSG:4326 isn't recognized as projection!
As you deliver GDAL with Java bindings, you can (should IMHO ;-)) include %SDK_ROOT%bin\gdal\java; in the PATH :

SET "PATH=%SDK_ROOT%bin;%SDK_ROOT%bin\gdal\java;%SDK_ROOT%bin\gdal\python\osgeo;%SDK_ROOT%bin\proj9\apps;%SDK_ROOT%bin\gdal\apps;%SDK_ROOT%bin\ms\apps;%SDK_ROOT%bin\gdal\csharp;%SDK_ROOT%bin\ms\csharp;%SDK_ROOT%bin\curl;%PATH%"
SET "GDAL_DATA=%SDK_ROOT%bin\gdal-data"
SET "GDAL_DRIVER_PATH=%SDK_ROOT%bin\gdal\plugins"
SET "PYTHONPATH=%SDK_ROOT%bin\gdal\python;%SDK_ROOT%bin\ms\python"
SET "PROJ_LIB=%SDK_ROOT%bin\proj9\SHARE"

**Comment by szekerest** [comment]
closing
